Update chocolatine.yml

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -10,7 +10,7 @@ on:
 
 env:
   EXECUTABLES: "directory1/executableA,directory2/executableB"
-  MIRROR_URL: " git@github.com:EpitechPGEPromo2029/B-DOP-200-PAR-2-1-chocolatine-sandra.kildemose-jorgensen.git"
+  MIRROR_URL: "git@github.com:EpitechPGEPromo2029/B-DOP-200-PAR-2-1-chocolatine-sandra.kildemose-jorgensen.git"
 
 jobs:
   check_conditions:
@@ -23,13 +23,11 @@ jobs:
         id: check
         run: |
           echo "Repository: $GITHUB_REPOSITORY"
-          if [ "$GITHUB_REPOSITORY" = " git@github.com:EpitechPGEPromo2029/B-DOP-200-PAR-2-1-chocolatine-sandra.kildemose-jorgensen.git" ]; then
+          if [ "$GITHUB_REPOSITORY" = "EpitechPGEPromo2029/B-DOP-200-PAR-2-1-chocolatine-sandra.kildemose-jorgensen" ]; then
             echo "result=false" >> $GITHUB_OUTPUT
           else
             echo "result=true" >> $GITHUB_OUTPUT
           fi
-
-
 
   check_coding_style:
     name: Check coding style
@@ -44,6 +42,7 @@ jobs:
 
       - name: Run coding style check
         run: check.sh $(pwd) $(pwd)
+
   check_program_compilation:
     name: Check program compilation
     needs: check_coding_style
@@ -64,15 +63,43 @@ jobs:
 
       - name: Check executables
         run: |
-
           echo "$EXECUTABLES" | tr ',' '\n' | while read -r file; do
             if [ ! -x "$file" ]; then
-          echo "::error file=$file::Missing or not executable: $file"
-          exit 1
-          fi
+              echo "::error file=$file::Missing or not executable: $file"
+              exit 1
+            fi
           done
-          
-         
+
+  run_tests:
+    name: Run tests
+    needs: check_program_compilation
+    if: needs.check_conditions.outputs.should_run == 'true'
+    runs-on: ubuntu-latest
+    container: epitechcontent/epitest-docker:latest
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Run tests
+        run: make tests_run
+        timeout-minutes: 2
+
+  push_to_mirror:
+    name: Push to mirror repository
+    needs: run_tests
+    if: github.event_name == 'push' && needs.check_conditions.outputs.should_run == 'true'
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Push to mirror
+        uses: pixta-dev/repository-mirroring-action@v1
+        with:
+          target_repo_url: ${{ env.MIRROR_URL }}
+          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
 
 
           
