Update chocolatine.yml

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -9,8 +9,8 @@ on:
       - "ga-ignore-*"
 
 env:
-  EXECUTABLES: "my_binary"  # ← SKIFT til navnet på din eksekverbare
-  MIRROR_URL: "git@github.com:EpitechPGEPromo2029/B-DOP-200-PAR-2-1-chocolatine-sandra.kildemose-jorgensen.git"
+  EXECUTABLES: "directory1/executableA,directory2/executableB"
+  MIRROR_URL: " git@github.com:EpitechPGEPromo2029/B-DOP-200-PAR-2-1-chocolatine-sandra.kildemose-jorgensen.git"
 
 jobs:
   check_conditions:
@@ -23,11 +23,13 @@ jobs:
         id: check
         run: |
           echo "Repository: $GITHUB_REPOSITORY"
-          if [ "$GITHUB_REPOSITORY" = "EpitechPGEPromo2029/B-DOP-200-PAR-2-1-chocolatine-sandra.kildemose-jorgensen" ]; then
+          if [ "$GITHUB_REPOSITORY" = " git@github.com:EpitechPGEPromo2029/B-DOP-200-PAR-2-1-chocolatine-sandra.kildemose-jorgensen.git" ]; then
             echo "result=false" >> $GITHUB_OUTPUT
           else
             echo "result=true" >> $GITHUB_OUTPUT
           fi
+
+
 
   check_coding_style:
     name: Check coding style
@@ -42,7 +44,6 @@ jobs:
 
       - name: Run coding style check
         run: check.sh $(pwd) $(pwd)
-
   check_program_compilation:
     name: Check program compilation
     needs: check_coding_style
@@ -58,48 +59,17 @@ jobs:
         run: make
         timeout-minutes: 2
 
+      - name: Run make clean
+        run: make clean
+
       - name: Check executables
         run: |
+
           echo "$EXECUTABLES" | tr ',' '\n' | while read -r file; do
             if [ ! -x "$file" ]; then
-              echo "::error file=$file::Missing or not executable: $file"
-              exit 1
-            fi
+          echo "::error file=$file::Missing or not executable: $file"
+          exit 1
+          fi
           done
-
-      - name: Run make clean
-        run: make clean || echo "::warning ::make clean failed"
-
-  run_tests:
-    name: Run tests
-    needs: check_program_compilation
-    if: needs.check_conditions.outputs.should_run == 'true'
-    runs-on: ubuntu-latest
-    container: epitechcontent/epitest-docker:latest
-
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-
-      - name: Run tests
-        run: make tests_run
-        timeout-minutes: 2
-
-  push_to_mirror:
-    name: Push to mirror repository
-    needs: run_tests
-    if: github.event_name == 'push' && needs.check_conditions.outputs.should_run == 'true'
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-
-      - name: Push to mirror
-        uses: pixta-dev/repository-mirroring-action@v1
-        with:
-          target_repo_url: ${{ env.MIRROR_URL }}
-          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
-
 
           
